export const NavbarData=[
    {
        id:1,
        name:"Home",
        path:"/",
    },
    {
        id:2,
        name:"About",
        path:"/",
    },
    {
        id:3,
        name:"Review",
        path:"/review",
    },
    {
        id:4,
        name:"Register",
        path:"/register",
    },
]